modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/Extegral/World-Name-Randomizer/issues" #optional
[[mods]] #mandatory
modId="worldnamerandomizer" #mandatory
version="1.0.0" #mandatory
displayName="World Name Randomizer" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/world-name-randomizer" #optional
logoFile="WNR_logo.png" #optional
credits="Me, for making such an amazing mod." #optional
authors="Integral" #optional
description='''
Simple mod that puts in random world name each time you're going to create new world.
'''
[[dependencies.worldnamerandomizer]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.worldnamerandomizer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"